name: flux_ci

on:
    schedule:
        - cron: "0 23 * * *"
    workflow_dispatch:
    push:
      branches:
        - main
        - dev
    
jobs:
    CreateImage:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Install PNPM
              uses: pnpm/action-setup@v3
              with:
                  version: ^7.0

            - name: Install Deps
              run: pnpm install --no-frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Create Image
              run: pnpm run start --token "${{ secrets.FLUX_TOKEN }}"

            - name: Push New Pic
              run: |
                  git config --local user.email "923828430@qq.com"
                  git config --local user.name "${{ github.actor }}"
                  git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git add .
                  git commit -m "generated today pic" || echo "no need to commit "
                  git pull origin dev --rebase
                  git push -f || echo "no file change"

            # 发送tg
            - name: send tg message
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                message: |
                  Push New Pic Today
                  ${{ github.actor }} created commit:
                  Repository: ${{ github.repository }}
                  See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
